import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import logo from './assets/logo.jfif';
import avatar from './assets/avatar.jpg';

const DEMO={admin:{name:'Bastaoang Jayson A',password:'webinternDEV'},hostPassword:'BSIT',userPassword:'CRT-NEUST-GSC'};
const defaultRooms=[{id:'room-1',title:'Web Development Class',host:'Jayson',participants:12,active:true},{id:'room-2',title:'Programming Class',host:'Maria',participants:7,active:true}];
function loadRooms(){try{return JSON.parse(localStorage.getItem('wid_rooms'))||defaultRooms}catch{return defaultRooms}}
function App(){
 const [role,setRole]=useState(null),[page,setPage]=useState('entry'),[name,setName]=useState(''),[password,setPassword]=useState(''),[rooms,setRooms]=useState(loadRooms),[currentRoom,setCurrentRoom]=useState(null),[camera,setCamera]=useState(false),[mic,setMic]=useState(true),[sharing,setSharing]=useState(false),[pinned,setPinned]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem('wid_rooms',JSON.stringify(rooms)),[rooms]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)}},[toast]);
 const activeRooms=useMemo(()=>rooms.filter(r=>r.active),[rooms]);
 function enterRole(r){setRole(r);setPage('login');setName('');setPassword('')}
 function login(e){e.preventDefault();
   const ok=role==='admin'?(name===DEMO.admin.name&&password===DEMO.admin.password):(role==='host'?password===DEMO.hostPassword:password===DEMO.userPassword);
   if(!ok){setToast('Invalid name or password.');return}
   setPage('dashboard');setToast(`Welcome to WebInternDev, ${name || role}!`)
 }
 function createRoom(){if(activeRooms.length>=2){setToast('Maximum of 2 active meeting rooms has been reached.');return} const title=prompt('Meeting title:','Web Development Class'); if(!title?.trim())return; const room={id:crypto.randomUUID(),title:title.trim(),host:name,participants:0,active:true};setRooms(x=>[...x,room]);setToast('Meeting created successfully.')}
 function joinRoom(room){if(role==='user'&&room.participants>=50){setToast('This meeting is full.');return}setCurrentRoom(room);setPage('meeting')}
 function endRoom(){if(!currentRoom)return;setRooms(x=>x.map(r=>r.id===currentRoom.id?{...r,active:false}:r));setCurrentRoom(null);setPage('dashboard');setSharing(false);setPinned(false);setToast('Meeting ended.')}
 function leaveMeeting(){setCurrentRoom(null);setPage('dashboard');setSharing(false);setPinned(false);setToast('You left the meeting. You can rejoin while it is active.')}
 return <div className="app">
  <header className="topbar"><button className="brand" onClick={()=>{setPage(role?'dashboard':'entry')}}><img src={logo}/><span>WebInternDev</span></button>{role&&<div className="top-actions"><span className="role-pill">{role==='admin'?'👑 Admin':role==='host'?'🎤 Host':'👤 User'}</span><button className="ghost" onClick={()=>{setRole(null);setPage('entry')}}>Sign out</button></div>}</header>
  <main>{page==='entry'&&<Entry onSelect={enterRole}/>} {page==='login'&&<Login role={role} name={name} setName={setName} password={password} setPassword={setPassword} onSubmit={login} onBack={()=>setPage('entry')}/>} {page==='dashboard'&&<Dashboard role={role} name={name} rooms={activeRooms} allRooms={rooms} onCreate={createRoom} onJoin={joinRoom} onEnd={r=>setRooms(x=>x.map(a=>a.id===r.id?{...a,active:false}:a))} onRejoin={joinRoom} />} {page==='meeting'&&<Meeting role={role} name={name} room={currentRoom} avatar={avatar} camera={camera} mic={mic} sharing={sharing} pinned={pinned} setCamera={setCamera} setMic={setMic} setSharing={setSharing} setPinned={setPinned} onLeave={leaveMeeting} onEnd={endRoom} />}</main>
  {toast&&<div className="toast">{toast}</div>}
  <footer>WebInternDev • Responsive meeting platform prototype</footer>
 </div>
}
function Entry({onSelect}){return <section className="hero"><div className="hero-card entry-card"><div className="hero-brand-wrap"><img className="hero-logo" src={logo}/></div><div className="entry-intro"><span className="entry-kicker">SECURE • SIMPLE • CONNECTED</span><h1>How do you want to enter?</h1><p>Select your role to continue to WebInternDev.</p></div><div className="role-grid"><button className="role-card" onClick={()=>onSelect('admin')}><span className="role-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 19.5V9.8L12 5l8 4.8v9.7"/><path d="M8 19.5v-6h8v6M3 19.5h18M9 9.5h6"/></svg></span><span>Admin</span><small>Monitor meetings and manage the platform</small><strong>Continue <i>→</i></strong></button><button className="role-card" onClick={()=>onSelect('host')}><span className="role-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m8 9 5 3-5 3V9ZM16 9h2M16 12h2M16 15h2"/></svg></span><span>Host</span><small>Create meetings and share your screen</small><strong>Continue <i>→</i></strong></button><button className="role-card" onClick={()=>onSelect('user')}><span className="role-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5.5 19c.8-3.2 3-5 6.5-5s5.7 1.8 6.5 5"/></svg></span><span>User</span><small>Join an active meeting and collaborate</small><strong>Continue <i>→</i></strong></button></div><div className="entry-footer"><span>WebInternDev</span><span>Professional meeting workspace</span></div></div></section>}
function Login({role,name,setName,password,setPassword,onSubmit,onBack}){return <section className="center"><div className="panel login-panel"><div className="panel-icon">{role==='admin'?'👑':role==='host'?'🎤':'👤'}</div><h1>{role==='admin'?'Admin Login':role==='host'?'Host Login':'User Login'}</h1><p className="muted">{role==='admin'?'Use the administrator account.':'Enter your name and shared role password.'}</p><form onSubmit={onSubmit}>{<label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder={role==='admin'?'Bastaoang Jayson A':'Enter your name'} required/></label>}<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/></label><button className="primary wide">Continue</button></form><button className="link-btn" onClick={onBack}>← Back</button></div></section>}
function Dashboard({role,name,rooms,allRooms,onCreate,onJoin,onEnd,onRejoin}){const active=rooms;return <section className="dashboard"><div className="welcome"><div><span className="eyebrow">Welcome to WebInternDev!</span><h1>{name||role}</h1><p className="muted">{role==='admin'?'Monitor and manage your meeting platform.':role==='host'?'Create a room and present to up to 50 participants.':'Choose an active meeting to join.'}</p></div>{role==='host'&&<button className="primary" onClick={onCreate}>＋ Create Meeting</button>}</div>{role==='admin'&&<div className="stats"><Stat n={active.length} t="Active Meetings"/><Stat n={active.reduce((a,r)=>a+r.participants,0)} t="Participants"/><Stat n="50" t="Capacity / Room"/><Stat n="2" t="Room Limit"/></div>}<div className="section-head"><h2>{role==='admin'?'Active Meetings':'Available Meetings'}</h2><span>{active.length}/2 active</span></div><div className="room-grid">{active.length?active.map(r=><RoomCard key={r.id} room={r} role={role} onJoin={()=>onJoin(r)} onEnd={()=>onEnd(r)} />):<div className="empty"><b>No active meetings</b><p>{role==='host'?'Create your first meeting to get started.':'Wait for a Host to create a meeting.'}</p></div>}</div>{role==='admin'&&<><div className="section-head"><h2>Platform controls</h2></div><div className="control-grid"><div className="panel"><b>👥 User Management</b><p className="muted">Manage user access and role passwords in the production Supabase backend.</p></div><div className="panel"><b>🔐 Password Management</b><p className="muted">Host and User passwords are planned to be managed securely by Admin.</p></div><div className="panel"><b>📋 Attendance</b><p className="muted">Join/leave timestamps and meeting history will be stored in Supabase.</p></div></div></>}</section>}
function Stat({n,t}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
function RoomCard({room,role,onJoin,onEnd}){return <div className="room-card"><div className="room-top"><span className="live">● LIVE</span><span>{room.participants}/50</span></div><h3>{room.title}</h3><p className="muted">Host: {room.host}</p><div className="room-actions">{role==='admin'?<button className="danger" onClick={onEnd}>End Meeting</button>:<button className="primary" onClick={onJoin}>{role==='host'?'Open Meeting':'Join Meeting'}</button>}</div></div>}
function Meeting({role,name,room,avatar,camera,mic,sharing,pinned,setCamera,setMic,setSharing,setPinned,onLeave,onEnd}){return <section className="meeting"><div className="meeting-head"><div><b>{room.title}</b><span className="muted"> • {room.participants}/50</span></div><span className="live">● LIVE</span></div><div className={"stage "+(pinned?'pinned':'')}><div className="main-tile">{sharing?<div className="share-preview"><div className="fake-slide"><span>WebInternDev Presentation</span><b>Screen sharing preview</b><small>In production, LiveKit publishes the Host screen here.</small></div><span className="share-label">🖥️ {name} is sharing screen</span></div>:camera?<div className="camera-preview">Camera preview</div>:<div className="avatar-view"><img src={avatar}/><span>{name}</span></div>}</div><div className="thumbs"><div className="thumb"><img src={avatar}/><span>{name} • {role}</span></div>{[1,2,3,4].map(i=><div className="thumb" key={i}><img src={avatar}/><span>Participant {i}</span></div>)}</div></div><div className="meeting-controls"><button className={mic?'control active':'control'} onClick={()=>setMic(!mic)}>{mic?'🎤':'🔇'}</button><button className={camera?'control active':'control'} onClick={()=>setCamera(!camera)}>{camera?'📹':'📷'}</button>{role==='host'&&<><button className={sharing?'control active':'control'} onClick={()=>{setSharing(!sharing);if(sharing)setPinned(false)}}>🖥️</button><button disabled={!sharing} className={pinned?'control active':'control'} onClick={()=>setPinned(!pinned)}>📌</button></>}<button className="control">💬</button><button className="control">👥</button>{role==='host'?<button className="danger control" onClick={onEnd}>End</button>:<button className="danger control" onClick={onLeave}>Leave</button>}</div>{role==='host'&&<div className="host-note">Host controls: screen share + pin/unpin. Pinning is responsive across desktop, tablet, and mobile.</div>}</section>}

createRoot(document.getElementById('root')).render(<App/>);
